// export const GAMES = [
//   {
//     image: "/pseudo-steam/factorio.jpg",
//     title: "Factorio",
//     description:
//       "Factorio is a game about building and maintaining factories. You will be mining resources, researching technologies, building infrastructure, automating production and fighting enemies. Use your creativity and problem-solving skills to create massive automated production lines in this highly addictive engineering simulation.",
//     price: "$30.00",
//     tags: ["Base Building", "Automation", "Strategy", "Crafting", "Management"],
//     category: "Strategy",
//     ageRating: "PEGI 7",
//     releaseDate: "2020",
//     developer: "Wube Software LTD.",
//     features: [
//       "Single-player",
//       "Multi-player",
//       "Steam Workshop",
//       "Steam Cloud",
//     ],
//   },
//   {
//     image: "/pseudo-steam/kingdom-come.png",
//     title: "Kingdom Come: Deliverance",
//     description:
//       "Kingdom Come: Deliverance is a story-driven open-world RPG that immerses you in an epic adventure in the Holy Roman Empire. Avenge your parents' death as you battle invading forces, go on game-changing quests, and make influential choices.",
//     price: "$29.99",
//     tags: ["RPG", "Medieval", "Open World", "Historical", "First-Person"],
//     category: "RPG",
//     ageRating: "PEGI 18",
//     releaseDate: "2018",
//     developer: "Warhorse Studios",
//     features: [
//       "Single-player",
//       "Full controller support",
//       "Steam Achievements",
//     ],
//   },
//   {
//     image: "/pseudo-steam/metin2.jpg",
//     title: "Metin2",
//     description:
//       "Metin2 is a free-to-play fantasy MMORPG that has been running since 2004. Set in a medieval Asian world, players can choose between multiple character classes, each with unique martial arts and magical abilities. Fight against other players in PvP or team up to tackle challenging dungeons.",
//     price: "Free to Play",
//     tags: ["MMORPG", "Fantasy", "PvP", "PvE", "Martial Arts"],
//     category: "MMORPG",
//     ageRating: "PEGI 12",
//     releaseDate: "2004",
//     developer: "Webzen",
//     features: ["Multi-player", "PvP", "PvE", "Guilds"],
//   },
//   {
//     image: "/pseudo-steam/minecraft.avif",
//     title: "Minecraft",
//     description:
//       "Minecraft is the ultimate sandbox game where your imagination is the only limit. Create anything from simple homes to complex machinery. Explore vast randomly generated worlds, craft tools and items, and play in various modes including survival, creative, and multiplayer. Regular updates keep adding new content and possibilities.",
//     price: "$26.95",
//     tags: ["Sandbox", "Crafting", "Survival", "Multiplayer", "Building"],
//     category: "Sandbox",
//     ageRating: "PEGI 7",
//     releaseDate: "2011",
//     developer: "Mojang Studios",
//     features: ["Single-player", "Multi-player", "Cross-Platform Multiplayer"],
//   },
//   {
//     image: "/pseudo-steam/rimworld.jpg",
//     title: "RimWorld",
//     description:
//       "RimWorld is a sci-fi colony simulation driven by an intelligent AI storyteller. Generate a random world and manage colonists with unique backgrounds, personalities, and skills. Face numerous challenges from pirates, hostile tribes, wild animals, and the harsh environment while building a thriving colony.",
//     price: "$34.99",
//     tags: ["Colony Sim", "Sci-Fi", "Management", "Strategy", "Survival"],
//     category: "Simulation",
//     ageRating: "PEGI 16",
//     releaseDate: "2018",
//     developer: "Ludeon Studios",
//     features: ["Single-player", "Moddable", "Steam Workshop"],
//   },
//   {
//     image: "/pseudo-steam/tibia.webp",
//     title: "Tibia",
//     description:
//       "One of the longest-running MMORPGs, Tibia offers a unique old-school gaming experience since 1997. With its distinctive 2D graphics, deep character progression system, and challenging gameplay, it maintains a dedicated community. Explore a vast world, hunt monsters, and develop your character with unlimited level progression.",
//     price: "Free to Play",
//     tags: ["MMORPG", "Fantasy", "PvE", "PvP", "Old-School"],
//     category: "MMORPG",
//     ageRating: "PEGI 12",
//     releaseDate: "1997",
//     developer: "CipSoft",
//     features: ["Multi-player", "PvE", "PvP", "Guilds"],
//   },
// ];
export const POPULAR_GAMES = [
  {
    image: "/pseudo-steam/factorio.jpg",
    title: "Factorio",
    description:
      "Factorio is a game about building and maintaining factories. Mine resources, research technologies, build infrastructure, automate production and fend off enemies.",
    price: "$30.00",
    tags: ["Base Building", "Automation", "Strategy", "Crafting", "Management"],
    category: "Strategy",
    ageRating: "PEGI 7",
    releaseDate: "2020",
    developer: "Wube Software LTD.",
    features: [
      "Single-player",
      "Multi-player",
      "Steam Workshop",
      "Steam Cloud",
    ],
  },
  {
    image: "/pseudo-steam/kingdom-come.png",
    title: "Kingdom Come: Deliverance",
    description:
      "A story-driven open-world RPG set in the Holy Roman Empire. Experience historical battles, challenging quests, and deep narrative choices.",
    price: "$29.99",
    tags: ["RPG", "Medieval", "Open World", "Historical", "First-Person"],
    category: "RPG",
    ageRating: "PEGI 18",
    releaseDate: "2018",
    developer: "Warhorse Studios",
    features: ["Single-player", "Controller support", "Steam Achievements"],
  },
  {
    image: "/pseudo-steam/minecraft.avif",
    title: "Minecraft",
    description:
      "The ultimate sandbox game where creativity meets survival. Build, explore, and conquer vast, randomly generated worlds with friends or solo.",
    price: "$26.95",
    tags: ["Sandbox", "Crafting", "Survival", "Multiplayer", "Building"],
    category: "Sandbox",
    ageRating: "PEGI 7",
    releaseDate: "2011",
    developer: "Mojang Studios",
    features: ["Single-player", "Multi-player", "Cross-Platform"],
  },
  {
    image: "/pseudo-steam/rimworld.jpg",
    title: "RimWorld",
    description:
      "A sci-fi colony simulation driven by an AI storyteller. Manage colonists with unique traits and face challenges in a procedurally generated world.",
    price: "$34.99",
    tags: ["Colony Sim", "Sci-Fi", "Management", "Strategy", "Survival"],
    category: "Simulation",
    ageRating: "PEGI 16",
    releaseDate: "2018",
    developer: "Ludeon Studios",
    features: ["Single-player", "Moddable", "Steam Workshop"],
  },
  {
    image: "/pseudo-steam/celeste.jpg",
    title: "Celeste",
    description:
      "Celeste is a platformer about overcoming challenges on and off the mountain. Master tricky jumps and explore a touching story of self-discovery.",
    price: "$19.99",
    tags: ["Platformer", "Indie", "Challenging", "Story-rich"],
    category: "Platformer",
    ageRating: "PEGI 7",
    releaseDate: "2018",
    developer: "Matt Makes Games",
    features: ["Single-player", "Precision platforming", "Pixel art"],
  },
  {
    image: "/pseudo-steam/hades.jpg",
    title: "Hades",
    description:
      "An award-winning rogue-like dungeon crawler where you battle out of hell. Enjoy fast-paced combat and an evolving story inspired by Greek mythology.",
    price: "$24.99",
    tags: ["Rogue-like", "Action", "Indie", "Mythology"],
    category: "Action",
    ageRating: "PEGI 12",
    releaseDate: "2020",
    developer: "Supergiant Games",
    features: ["Single-player", "Rogue-like", "Narrative-driven", "Fast-paced"],
  },
];

export const UPCOMING_GAMES = [
  {
    image: "/starbound-odyssey.jpg",
    title: "Starbound Odyssey",
    description:
      "Embark on a thrilling space adventure, exploring alien worlds and uncovering cosmic secrets in this epic sci-fi RPG.",
    price: "$49.99",
    tags: ["Sci-Fi", "Exploration", "Space", "RPG"],
    category: "Sci-Fi RPG",
    ageRating: "PEGI 12",
    releaseDate: "2025",
    developer: "Galactic Forge Studios",
    features: ["Open world", "Multiplayer", "Dynamic events"],
  },
  {
    image: "/mystic-realms.jpg",
    title: "Mystic Realms",
    description:
      "Step into a magical world full of enchantment and mystery. Master spells and battle mythical creatures in an immersive fantasy adventure.",
    price: "$39.99",
    tags: ["Fantasy", "RPG", "Adventure"],
    category: "Fantasy RPG",
    ageRating: "PEGI 12",
    releaseDate: "2025",
    developer: "Enchanted Games",
    features: ["Single-player", "Rich storytelling", "Open world"],
  },
  {
    image: "/racing-legends-2.jpg",
    title: "Racing Legends 2",
    description:
      "Take to the streets in high-octane races, customize your ride and compete in dynamic urban environments to become a racing legend.",
    price: "$29.99",
    tags: ["Racing", "Sports", "Multiplayer"],
    category: "Racing",
    ageRating: "PEGI 3",
    releaseDate: "2024",
    developer: "Velocity Games",
    features: ["Multiplayer", "Customization", "Realistic physics"],
  },
  {
    image: "/dreamscape.jpg",
    title: "Dreamscape",
    description:
      "Enter a surreal world where dreams and reality collide. Solve innovative puzzles and explore visually stunning landscapes.",
    price: "$19.99",
    tags: ["Puzzle", "Adventure", "Indie"],
    category: "Puzzle Adventure",
    ageRating: "PEGI 7",
    releaseDate: "2024",
    developer: "MindBend Studios",
    features: ["Single-player", "Artistic design", "Innovative puzzles"],
  },
  {
    image: "/battlefront-chronicles.jpg",
    title: "Battlefront Chronicles",
    description:
      "Command armies and rewrite history in epic battles across sprawling battlefields. Engage in deep strategic warfare with friends or solo.",
    price: "$59.99",
    tags: ["Strategy", "War", "Multiplayer"],
    category: "Strategy",
    ageRating: "PEGI 16",
    releaseDate: "2025",
    developer: "Warpath Studios",
    features: ["Multiplayer", "Deep strategy", "Historical settings"],
  },
  {
    image: "/oceanic-quest.jpg",
    title: "Oceanic Quest",
    description:
      "Dive into the mysteries of the deep sea, uncover sunken treasures, and battle mythical sea monsters in this action-packed adventure.",
    price: "$34.99",
    tags: ["Adventure", "Exploration", "Action"],
    category: "Action Adventure",
    ageRating: "PEGI 12",
    releaseDate: "2024",
    developer: "Blue Horizon Games",
    features: ["Open world", "Underwater exploration", "Dynamic weather"],
  },
];

export const FREE_GAMES = [
  {
    image: "/pseudo-steam/metin2.jpg",
    title: "Metin2",
    description:
      "A free-to-play fantasy MMORPG set in a mystical world. Battle epic foes, explore vast lands and join forces with players worldwide.",
    price: "Free to Play",
    tags: ["MMORPG", "Fantasy", "PvP", "PvE", "Martial Arts"],
    category: "MMORPG",
    ageRating: "PEGI 12",
    releaseDate: "2004",
    developer: "Webzen",
    features: ["Multi-player", "PvP", "PvE", "Guilds"],
  },
  {
    image: "/pseudo-steam/tibia.webp",
    title: "Tibia",
    description:
      "Experience a classic MMORPG with deep character progression and challenging gameplay in a long-running title with a dedicated community.",
    price: "Free to Play",
    tags: ["MMORPG", "Fantasy", "PvE", "PvP", "Old-School"],
    category: "MMORPG",
    ageRating: "PEGI 12",
    releaseDate: "1997",
    developer: "CipSoft",
    features: ["Multi-player", "PvE", "PvP", "Guilds"],
  },
  {
    image: "/pseudo-steam/warframe.jpg",
    title: "Warframe",
    description:
      "A cooperative free-to-play third-person shooter set in an evolving sci-fi world. Master your Warframe and join fast-paced missions.",
    price: "Free to Play",
    tags: ["Shooter", "Sci-Fi", "Action", "Multiplayer"],
    category: "Action",
    ageRating: "PEGI 12",
    releaseDate: "2013",
    developer: "Digital Extremes",
    features: ["Co-op", "Fast-paced", "Customization"],
  },
  {
    image: "/pseudo-steam/fortnite.jpg",
    title: "Fortnite",
    description:
      "A battle royale game where players fight to be the last one standing. Enjoy regular updates, events, and a vibrant community.",
    price: "Free to Play",
    tags: ["Battle Royale", "Shooter", "Multiplayer"],
    category: "Battle Royale",
    ageRating: "PEGI 12",
    releaseDate: "2017",
    developer: "Epic Games",
    features: ["Multiplayer", "Regular updates", "Cross-platform"],
  },
  {
    image: "/pseudo-steam/genshin-impact.jpg",
    title: "Genshin Impact",
    description:
      "Explore a vast open world filled with elemental magic in this free-to-play action RPG. Uncover secrets and enjoy dynamic combat.",
    price: "Free to Play",
    tags: ["RPG", "Adventure", "Open World", "Fantasy"],
    category: "Action RPG",
    ageRating: "PEGI 12",
    releaseDate: "2020",
    developer: "miHoYo",
    features: ["Open world", "Action combat", "Gacha elements"],
  },
  {
    image: "/pseudo-steam/apex-legends.jpg",
    title: "Apex Legends",
    description:
      "A squad-based battle royale that mixes hero shooter mechanics with fast-paced, tactical combat. Jump into intense multiplayer battles.",
    price: "Free to Play",
    tags: ["Battle Royale", "Shooter", "Multiplayer"],
    category: "Battle Royale",
    ageRating: "PEGI 16",
    releaseDate: "2019",
    developer: "Respawn Entertainment",
    features: ["Multiplayer", "Team-based", "Tactical gameplay"],
  },
];
